version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ia
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 697932
      POSTGRES_DB: finance-ai
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-date:
